// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoEntity.proto

package com.centling.protobuf;

public final class ProtoEntity {
  private ProtoEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bean.Entity)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string attrcd = 1;</code>
     */
    boolean hasAttrcd();
    /**
     * <code>optional string attrcd = 1;</code>
     */
    java.lang.String getAttrcd();
    /**
     * <code>optional string attrcd = 1;</code>
     */
    com.google.protobuf.ByteString
        getAttrcdBytes();

    /**
     * <code>optional string cd = 2;</code>
     */
    boolean hasCd();
    /**
     * <code>optional string cd = 2;</code>
     */
    java.lang.String getCd();
    /**
     * <code>optional string cd = 2;</code>
     */
    com.google.protobuf.ByteString
        getCdBytes();

    /**
     * <code>optional string speccn = 3;</code>
     */
    boolean hasSpeccn();
    /**
     * <code>optional string speccn = 3;</code>
     */
    java.lang.String getSpeccn();
    /**
     * <code>optional string speccn = 3;</code>
     */
    com.google.protobuf.ByteString
        getSpeccnBytes();

    /**
     * <code>optional string specen = 4;</code>
     */
    boolean hasSpecen();
    /**
     * <code>optional string specen = 4;</code>
     */
    java.lang.String getSpecen();
    /**
     * <code>optional string specen = 4;</code>
     */
    com.google.protobuf.ByteString
        getSpecenBytes();

    /**
     * <code>optional string statecd = 5;</code>
     */
    boolean hasStatecd();
    /**
     * <code>optional string statecd = 5;</code>
     */
    java.lang.String getStatecd();
    /**
     * <code>optional string statecd = 5;</code>
     */
    com.google.protobuf.ByteString
        getStatecdBytes();

    /**
     * <code>optional string statenm = 6;</code>
     */
    boolean hasStatenm();
    /**
     * <code>optional string statenm = 6;</code>
     */
    java.lang.String getStatenm();
    /**
     * <code>optional string statenm = 6;</code>
     */
    com.google.protobuf.ByteString
        getStatenmBytes();

    /**
     * <code>optional string countrycd = 7;</code>
     */
    boolean hasCountrycd();
    /**
     * <code>optional string countrycd = 7;</code>
     */
    java.lang.String getCountrycd();
    /**
     * <code>optional string countrycd = 7;</code>
     */
    com.google.protobuf.ByteString
        getCountrycdBytes();

    /**
     * <code>optional string countrynm = 8;</code>
     */
    boolean hasCountrynm();
    /**
     * <code>optional string countrynm = 8;</code>
     */
    java.lang.String getCountrynm();
    /**
     * <code>optional string countrynm = 8;</code>
     */
    com.google.protobuf.ByteString
        getCountrynmBytes();
  }
  /**
   * Protobuf type {@code bean.Entity}
   */
  public  static final class Entity extends
      com.google.protobuf.GeneratedMessageLite<
          Entity, Entity.Builder> implements
      // @@protoc_insertion_point(message_implements:bean.Entity)
      EntityOrBuilder {
    private Entity() {
      attrcd_ = "";
      cd_ = "";
      speccn_ = "";
      specen_ = "";
      statecd_ = "";
      statenm_ = "";
      countrycd_ = "";
      countrynm_ = "";
    }
    private int bitField0_;
    public static final int ATTRCD_FIELD_NUMBER = 1;
    private java.lang.String attrcd_;
    /**
     * <code>optional string attrcd = 1;</code>
     */
    public boolean hasAttrcd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string attrcd = 1;</code>
     */
    public java.lang.String getAttrcd() {
      return attrcd_;
    }
    /**
     * <code>optional string attrcd = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAttrcdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(attrcd_);
    }
    /**
     * <code>optional string attrcd = 1;</code>
     */
    private void setAttrcd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      attrcd_ = value;
    }
    /**
     * <code>optional string attrcd = 1;</code>
     */
    private void clearAttrcd() {
      bitField0_ = (bitField0_ & ~0x00000001);
      attrcd_ = getDefaultInstance().getAttrcd();
    }
    /**
     * <code>optional string attrcd = 1;</code>
     */
    private void setAttrcdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      attrcd_ = value.toStringUtf8();
    }

    public static final int CD_FIELD_NUMBER = 2;
    private java.lang.String cd_;
    /**
     * <code>optional string cd = 2;</code>
     */
    public boolean hasCd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string cd = 2;</code>
     */
    public java.lang.String getCd() {
      return cd_;
    }
    /**
     * <code>optional string cd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cd_);
    }
    /**
     * <code>optional string cd = 2;</code>
     */
    private void setCd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      cd_ = value;
    }
    /**
     * <code>optional string cd = 2;</code>
     */
    private void clearCd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cd_ = getDefaultInstance().getCd();
    }
    /**
     * <code>optional string cd = 2;</code>
     */
    private void setCdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      cd_ = value.toStringUtf8();
    }

    public static final int SPECCN_FIELD_NUMBER = 3;
    private java.lang.String speccn_;
    /**
     * <code>optional string speccn = 3;</code>
     */
    public boolean hasSpeccn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string speccn = 3;</code>
     */
    public java.lang.String getSpeccn() {
      return speccn_;
    }
    /**
     * <code>optional string speccn = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSpeccnBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(speccn_);
    }
    /**
     * <code>optional string speccn = 3;</code>
     */
    private void setSpeccn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      speccn_ = value;
    }
    /**
     * <code>optional string speccn = 3;</code>
     */
    private void clearSpeccn() {
      bitField0_ = (bitField0_ & ~0x00000004);
      speccn_ = getDefaultInstance().getSpeccn();
    }
    /**
     * <code>optional string speccn = 3;</code>
     */
    private void setSpeccnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      speccn_ = value.toStringUtf8();
    }

    public static final int SPECEN_FIELD_NUMBER = 4;
    private java.lang.String specen_;
    /**
     * <code>optional string specen = 4;</code>
     */
    public boolean hasSpecen() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string specen = 4;</code>
     */
    public java.lang.String getSpecen() {
      return specen_;
    }
    /**
     * <code>optional string specen = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSpecenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(specen_);
    }
    /**
     * <code>optional string specen = 4;</code>
     */
    private void setSpecen(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      specen_ = value;
    }
    /**
     * <code>optional string specen = 4;</code>
     */
    private void clearSpecen() {
      bitField0_ = (bitField0_ & ~0x00000008);
      specen_ = getDefaultInstance().getSpecen();
    }
    /**
     * <code>optional string specen = 4;</code>
     */
    private void setSpecenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      specen_ = value.toStringUtf8();
    }

    public static final int STATECD_FIELD_NUMBER = 5;
    private java.lang.String statecd_;
    /**
     * <code>optional string statecd = 5;</code>
     */
    public boolean hasStatecd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string statecd = 5;</code>
     */
    public java.lang.String getStatecd() {
      return statecd_;
    }
    /**
     * <code>optional string statecd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStatecdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(statecd_);
    }
    /**
     * <code>optional string statecd = 5;</code>
     */
    private void setStatecd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      statecd_ = value;
    }
    /**
     * <code>optional string statecd = 5;</code>
     */
    private void clearStatecd() {
      bitField0_ = (bitField0_ & ~0x00000010);
      statecd_ = getDefaultInstance().getStatecd();
    }
    /**
     * <code>optional string statecd = 5;</code>
     */
    private void setStatecdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      statecd_ = value.toStringUtf8();
    }

    public static final int STATENM_FIELD_NUMBER = 6;
    private java.lang.String statenm_;
    /**
     * <code>optional string statenm = 6;</code>
     */
    public boolean hasStatenm() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string statenm = 6;</code>
     */
    public java.lang.String getStatenm() {
      return statenm_;
    }
    /**
     * <code>optional string statenm = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStatenmBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(statenm_);
    }
    /**
     * <code>optional string statenm = 6;</code>
     */
    private void setStatenm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      statenm_ = value;
    }
    /**
     * <code>optional string statenm = 6;</code>
     */
    private void clearStatenm() {
      bitField0_ = (bitField0_ & ~0x00000020);
      statenm_ = getDefaultInstance().getStatenm();
    }
    /**
     * <code>optional string statenm = 6;</code>
     */
    private void setStatenmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      statenm_ = value.toStringUtf8();
    }

    public static final int COUNTRYCD_FIELD_NUMBER = 7;
    private java.lang.String countrycd_;
    /**
     * <code>optional string countrycd = 7;</code>
     */
    public boolean hasCountrycd() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string countrycd = 7;</code>
     */
    public java.lang.String getCountrycd() {
      return countrycd_;
    }
    /**
     * <code>optional string countrycd = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCountrycdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(countrycd_);
    }
    /**
     * <code>optional string countrycd = 7;</code>
     */
    private void setCountrycd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      countrycd_ = value;
    }
    /**
     * <code>optional string countrycd = 7;</code>
     */
    private void clearCountrycd() {
      bitField0_ = (bitField0_ & ~0x00000040);
      countrycd_ = getDefaultInstance().getCountrycd();
    }
    /**
     * <code>optional string countrycd = 7;</code>
     */
    private void setCountrycdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      countrycd_ = value.toStringUtf8();
    }

    public static final int COUNTRYNM_FIELD_NUMBER = 8;
    private java.lang.String countrynm_;
    /**
     * <code>optional string countrynm = 8;</code>
     */
    public boolean hasCountrynm() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string countrynm = 8;</code>
     */
    public java.lang.String getCountrynm() {
      return countrynm_;
    }
    /**
     * <code>optional string countrynm = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCountrynmBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(countrynm_);
    }
    /**
     * <code>optional string countrynm = 8;</code>
     */
    private void setCountrynm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      countrynm_ = value;
    }
    /**
     * <code>optional string countrynm = 8;</code>
     */
    private void clearCountrynm() {
      bitField0_ = (bitField0_ & ~0x00000080);
      countrynm_ = getDefaultInstance().getCountrynm();
    }
    /**
     * <code>optional string countrynm = 8;</code>
     */
    private void setCountrynmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      countrynm_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getAttrcd());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getCd());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getSpeccn());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(4, getSpecen());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeString(5, getStatecd());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeString(6, getStatenm());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeString(7, getCountrycd());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeString(8, getCountrynm());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAttrcd());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getCd());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSpeccn());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSpecen());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getStatecd());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getStatenm());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getCountrycd());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getCountrynm());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.centling.protobuf.ProtoEntity.Entity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.centling.protobuf.ProtoEntity.Entity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code bean.Entity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.centling.protobuf.ProtoEntity.Entity, Builder> implements
        // @@protoc_insertion_point(builder_implements:bean.Entity)
        com.centling.protobuf.ProtoEntity.EntityOrBuilder {
      // Construct using com.centling.protobuf.ProtoEntity.Entity.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string attrcd = 1;</code>
       */
      public boolean hasAttrcd() {
        return instance.hasAttrcd();
      }
      /**
       * <code>optional string attrcd = 1;</code>
       */
      public java.lang.String getAttrcd() {
        return instance.getAttrcd();
      }
      /**
       * <code>optional string attrcd = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAttrcdBytes() {
        return instance.getAttrcdBytes();
      }
      /**
       * <code>optional string attrcd = 1;</code>
       */
      public Builder setAttrcd(
          java.lang.String value) {
        copyOnWrite();
        instance.setAttrcd(value);
        return this;
      }
      /**
       * <code>optional string attrcd = 1;</code>
       */
      public Builder clearAttrcd() {
        copyOnWrite();
        instance.clearAttrcd();
        return this;
      }
      /**
       * <code>optional string attrcd = 1;</code>
       */
      public Builder setAttrcdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAttrcdBytes(value);
        return this;
      }

      /**
       * <code>optional string cd = 2;</code>
       */
      public boolean hasCd() {
        return instance.hasCd();
      }
      /**
       * <code>optional string cd = 2;</code>
       */
      public java.lang.String getCd() {
        return instance.getCd();
      }
      /**
       * <code>optional string cd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCdBytes() {
        return instance.getCdBytes();
      }
      /**
       * <code>optional string cd = 2;</code>
       */
      public Builder setCd(
          java.lang.String value) {
        copyOnWrite();
        instance.setCd(value);
        return this;
      }
      /**
       * <code>optional string cd = 2;</code>
       */
      public Builder clearCd() {
        copyOnWrite();
        instance.clearCd();
        return this;
      }
      /**
       * <code>optional string cd = 2;</code>
       */
      public Builder setCdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCdBytes(value);
        return this;
      }

      /**
       * <code>optional string speccn = 3;</code>
       */
      public boolean hasSpeccn() {
        return instance.hasSpeccn();
      }
      /**
       * <code>optional string speccn = 3;</code>
       */
      public java.lang.String getSpeccn() {
        return instance.getSpeccn();
      }
      /**
       * <code>optional string speccn = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSpeccnBytes() {
        return instance.getSpeccnBytes();
      }
      /**
       * <code>optional string speccn = 3;</code>
       */
      public Builder setSpeccn(
          java.lang.String value) {
        copyOnWrite();
        instance.setSpeccn(value);
        return this;
      }
      /**
       * <code>optional string speccn = 3;</code>
       */
      public Builder clearSpeccn() {
        copyOnWrite();
        instance.clearSpeccn();
        return this;
      }
      /**
       * <code>optional string speccn = 3;</code>
       */
      public Builder setSpeccnBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSpeccnBytes(value);
        return this;
      }

      /**
       * <code>optional string specen = 4;</code>
       */
      public boolean hasSpecen() {
        return instance.hasSpecen();
      }
      /**
       * <code>optional string specen = 4;</code>
       */
      public java.lang.String getSpecen() {
        return instance.getSpecen();
      }
      /**
       * <code>optional string specen = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSpecenBytes() {
        return instance.getSpecenBytes();
      }
      /**
       * <code>optional string specen = 4;</code>
       */
      public Builder setSpecen(
          java.lang.String value) {
        copyOnWrite();
        instance.setSpecen(value);
        return this;
      }
      /**
       * <code>optional string specen = 4;</code>
       */
      public Builder clearSpecen() {
        copyOnWrite();
        instance.clearSpecen();
        return this;
      }
      /**
       * <code>optional string specen = 4;</code>
       */
      public Builder setSpecenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSpecenBytes(value);
        return this;
      }

      /**
       * <code>optional string statecd = 5;</code>
       */
      public boolean hasStatecd() {
        return instance.hasStatecd();
      }
      /**
       * <code>optional string statecd = 5;</code>
       */
      public java.lang.String getStatecd() {
        return instance.getStatecd();
      }
      /**
       * <code>optional string statecd = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStatecdBytes() {
        return instance.getStatecdBytes();
      }
      /**
       * <code>optional string statecd = 5;</code>
       */
      public Builder setStatecd(
          java.lang.String value) {
        copyOnWrite();
        instance.setStatecd(value);
        return this;
      }
      /**
       * <code>optional string statecd = 5;</code>
       */
      public Builder clearStatecd() {
        copyOnWrite();
        instance.clearStatecd();
        return this;
      }
      /**
       * <code>optional string statecd = 5;</code>
       */
      public Builder setStatecdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStatecdBytes(value);
        return this;
      }

      /**
       * <code>optional string statenm = 6;</code>
       */
      public boolean hasStatenm() {
        return instance.hasStatenm();
      }
      /**
       * <code>optional string statenm = 6;</code>
       */
      public java.lang.String getStatenm() {
        return instance.getStatenm();
      }
      /**
       * <code>optional string statenm = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStatenmBytes() {
        return instance.getStatenmBytes();
      }
      /**
       * <code>optional string statenm = 6;</code>
       */
      public Builder setStatenm(
          java.lang.String value) {
        copyOnWrite();
        instance.setStatenm(value);
        return this;
      }
      /**
       * <code>optional string statenm = 6;</code>
       */
      public Builder clearStatenm() {
        copyOnWrite();
        instance.clearStatenm();
        return this;
      }
      /**
       * <code>optional string statenm = 6;</code>
       */
      public Builder setStatenmBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStatenmBytes(value);
        return this;
      }

      /**
       * <code>optional string countrycd = 7;</code>
       */
      public boolean hasCountrycd() {
        return instance.hasCountrycd();
      }
      /**
       * <code>optional string countrycd = 7;</code>
       */
      public java.lang.String getCountrycd() {
        return instance.getCountrycd();
      }
      /**
       * <code>optional string countrycd = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCountrycdBytes() {
        return instance.getCountrycdBytes();
      }
      /**
       * <code>optional string countrycd = 7;</code>
       */
      public Builder setCountrycd(
          java.lang.String value) {
        copyOnWrite();
        instance.setCountrycd(value);
        return this;
      }
      /**
       * <code>optional string countrycd = 7;</code>
       */
      public Builder clearCountrycd() {
        copyOnWrite();
        instance.clearCountrycd();
        return this;
      }
      /**
       * <code>optional string countrycd = 7;</code>
       */
      public Builder setCountrycdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountrycdBytes(value);
        return this;
      }

      /**
       * <code>optional string countrynm = 8;</code>
       */
      public boolean hasCountrynm() {
        return instance.hasCountrynm();
      }
      /**
       * <code>optional string countrynm = 8;</code>
       */
      public java.lang.String getCountrynm() {
        return instance.getCountrynm();
      }
      /**
       * <code>optional string countrynm = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCountrynmBytes() {
        return instance.getCountrynmBytes();
      }
      /**
       * <code>optional string countrynm = 8;</code>
       */
      public Builder setCountrynm(
          java.lang.String value) {
        copyOnWrite();
        instance.setCountrynm(value);
        return this;
      }
      /**
       * <code>optional string countrynm = 8;</code>
       */
      public Builder clearCountrynm() {
        copyOnWrite();
        instance.clearCountrynm();
        return this;
      }
      /**
       * <code>optional string countrynm = 8;</code>
       */
      public Builder setCountrynmBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountrynmBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.Entity)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.centling.protobuf.ProtoEntity.Entity();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.centling.protobuf.ProtoEntity.Entity other = (com.centling.protobuf.ProtoEntity.Entity) arg1;
          attrcd_ = visitor.visitString(
              hasAttrcd(), attrcd_,
              other.hasAttrcd(), other.attrcd_);
          cd_ = visitor.visitString(
              hasCd(), cd_,
              other.hasCd(), other.cd_);
          speccn_ = visitor.visitString(
              hasSpeccn(), speccn_,
              other.hasSpeccn(), other.speccn_);
          specen_ = visitor.visitString(
              hasSpecen(), specen_,
              other.hasSpecen(), other.specen_);
          statecd_ = visitor.visitString(
              hasStatecd(), statecd_,
              other.hasStatecd(), other.statecd_);
          statenm_ = visitor.visitString(
              hasStatenm(), statenm_,
              other.hasStatenm(), other.statenm_);
          countrycd_ = visitor.visitString(
              hasCountrycd(), countrycd_,
              other.hasCountrycd(), other.countrycd_);
          countrynm_ = visitor.visitString(
              hasCountrynm(), countrynm_,
              other.hasCountrynm(), other.countrynm_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  attrcd_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  cd_ = s;
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  speccn_ = s;
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  specen_ = s;
                  break;
                }
                case 42: {
                  String s = input.readString();
                  bitField0_ |= 0x00000010;
                  statecd_ = s;
                  break;
                }
                case 50: {
                  String s = input.readString();
                  bitField0_ |= 0x00000020;
                  statenm_ = s;
                  break;
                }
                case 58: {
                  String s = input.readString();
                  bitField0_ |= 0x00000040;
                  countrycd_ = s;
                  break;
                }
                case 66: {
                  String s = input.readString();
                  bitField0_ |= 0x00000080;
                  countrynm_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.centling.protobuf.ProtoEntity.Entity.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:bean.Entity)
    private static final com.centling.protobuf.ProtoEntity.Entity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Entity();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.centling.protobuf.ProtoEntity.Entity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Entity> PARSER;

    public static com.google.protobuf.Parser<Entity> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface basecodelistOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bean.basecodelist)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    java.util.List<com.centling.protobuf.ProtoEntity.Entity> 
        getEntityList();
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    com.centling.protobuf.ProtoEntity.Entity getEntity(int index);
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    int getEntityCount();
  }
  /**
   * Protobuf type {@code bean.basecodelist}
   */
  public  static final class basecodelist extends
      com.google.protobuf.GeneratedMessageLite<
          basecodelist, basecodelist.Builder> implements
      // @@protoc_insertion_point(message_implements:bean.basecodelist)
      basecodelistOrBuilder {
    private basecodelist() {
      entity_ = emptyProtobufList();
    }
    public static final int ENTITY_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.centling.protobuf.ProtoEntity.Entity> entity_;
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    public java.util.List<com.centling.protobuf.ProtoEntity.Entity> getEntityList() {
      return entity_;
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    public java.util.List<? extends com.centling.protobuf.ProtoEntity.EntityOrBuilder> 
        getEntityOrBuilderList() {
      return entity_;
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    public int getEntityCount() {
      return entity_.size();
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    public com.centling.protobuf.ProtoEntity.Entity getEntity(int index) {
      return entity_.get(index);
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    public com.centling.protobuf.ProtoEntity.EntityOrBuilder getEntityOrBuilder(
        int index) {
      return entity_.get(index);
    }
    private void ensureEntityIsMutable() {
      if (!entity_.isModifiable()) {
        entity_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(entity_);
       }
    }

    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void setEntity(
        int index, com.centling.protobuf.ProtoEntity.Entity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEntityIsMutable();
      entity_.set(index, value);
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void setEntity(
        int index, com.centling.protobuf.ProtoEntity.Entity.Builder builderForValue) {
      ensureEntityIsMutable();
      entity_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void addEntity(com.centling.protobuf.ProtoEntity.Entity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEntityIsMutable();
      entity_.add(value);
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void addEntity(
        int index, com.centling.protobuf.ProtoEntity.Entity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEntityIsMutable();
      entity_.add(index, value);
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void addEntity(
        com.centling.protobuf.ProtoEntity.Entity.Builder builderForValue) {
      ensureEntityIsMutable();
      entity_.add(builderForValue.build());
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void addEntity(
        int index, com.centling.protobuf.ProtoEntity.Entity.Builder builderForValue) {
      ensureEntityIsMutable();
      entity_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void addAllEntity(
        java.lang.Iterable<? extends com.centling.protobuf.ProtoEntity.Entity> values) {
      ensureEntityIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, entity_);
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void clearEntity() {
      entity_ = emptyProtobufList();
    }
    /**
     * <code>repeated .bean.Entity entity = 1;</code>
     */
    private void removeEntity(int index) {
      ensureEntityIsMutable();
      entity_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < entity_.size(); i++) {
        output.writeMessage(1, entity_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entity_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entity_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.centling.protobuf.ProtoEntity.basecodelist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.centling.protobuf.ProtoEntity.basecodelist prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code bean.basecodelist}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.centling.protobuf.ProtoEntity.basecodelist, Builder> implements
        // @@protoc_insertion_point(builder_implements:bean.basecodelist)
        com.centling.protobuf.ProtoEntity.basecodelistOrBuilder {
      // Construct using com.centling.protobuf.ProtoEntity.basecodelist.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public java.util.List<com.centling.protobuf.ProtoEntity.Entity> getEntityList() {
        return java.util.Collections.unmodifiableList(
            instance.getEntityList());
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public int getEntityCount() {
        return instance.getEntityCount();
      }/**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public com.centling.protobuf.ProtoEntity.Entity getEntity(int index) {
        return instance.getEntity(index);
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder setEntity(
          int index, com.centling.protobuf.ProtoEntity.Entity value) {
        copyOnWrite();
        instance.setEntity(index, value);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder setEntity(
          int index, com.centling.protobuf.ProtoEntity.Entity.Builder builderForValue) {
        copyOnWrite();
        instance.setEntity(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder addEntity(com.centling.protobuf.ProtoEntity.Entity value) {
        copyOnWrite();
        instance.addEntity(value);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder addEntity(
          int index, com.centling.protobuf.ProtoEntity.Entity value) {
        copyOnWrite();
        instance.addEntity(index, value);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder addEntity(
          com.centling.protobuf.ProtoEntity.Entity.Builder builderForValue) {
        copyOnWrite();
        instance.addEntity(builderForValue);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder addEntity(
          int index, com.centling.protobuf.ProtoEntity.Entity.Builder builderForValue) {
        copyOnWrite();
        instance.addEntity(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder addAllEntity(
          java.lang.Iterable<? extends com.centling.protobuf.ProtoEntity.Entity> values) {
        copyOnWrite();
        instance.addAllEntity(values);
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder clearEntity() {
        copyOnWrite();
        instance.clearEntity();
        return this;
      }
      /**
       * <code>repeated .bean.Entity entity = 1;</code>
       */
      public Builder removeEntity(int index) {
        copyOnWrite();
        instance.removeEntity(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.basecodelist)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.centling.protobuf.ProtoEntity.basecodelist();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          entity_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.centling.protobuf.ProtoEntity.basecodelist other = (com.centling.protobuf.ProtoEntity.basecodelist) arg1;
          entity_= visitor.visitList(entity_, other.entity_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!entity_.isModifiable()) {
                    entity_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(entity_);
                  }
                  entity_.add(
                      input.readMessage(com.centling.protobuf.ProtoEntity.Entity.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.centling.protobuf.ProtoEntity.basecodelist.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:bean.basecodelist)
    private static final com.centling.protobuf.ProtoEntity.basecodelist DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new basecodelist();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.centling.protobuf.ProtoEntity.basecodelist getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<basecodelist> PARSER;

    public static com.google.protobuf.Parser<basecodelist> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
